name: Pull Request Verify
on: pull_request
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: adopt-hotspot

      - name: Run tests and build app with Maven
        run: mvn clean install

      - name: Docker Compose Build
        run: |
          docker compose build
        working-directory: ./docker

      - name: Run tests and build app with Maven
        run: mvn clean install
